In [1]:
# %matplotlib inline is a special Jupyter Notebook magic command used with Python plotting libraries like Matplotlib.
#It tells Jupyter: “Display plots directly inside the notebook output cells.” Recent versions of Jupyter might not need it any more
# This notebook is based on the official PyTorch Tutorial: https://docs.pytorch.org/tutorials/beginner/colab
%matplotlib inline

Tensors
=======

Tensors are a specialized data structure that are very similar to arrays
and matrices. In PyTorch, we use tensors to encode the inputs and
outputs of a model, as well as the model's parameters.

Tensors are similar to NumPy's ndarrays, except that tensors can run on
GPUs or other specialized hardware to accelerate computing. If you're
familiar with ndarrays, you'll be right at home with the Tensor API. If
not, follow along in this quick API walkthrough.


In [2]:
import torch
import numpy as np

Tensor Initialization
=====================

Tensors can be initialized in various ways. Take a look at the following
examples:

**Directly from data**

Tensors can be created directly from data. The data type is
automatically inferred.


In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


**From a NumPy array**

Tensors can be created from NumPy arrays (and vice versa - see
`bridge-to-np-label`{.interpreted-text role="ref"}).


In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


**From another tensor:**

The new tensor retains the properties (shape, datatype) of the argument
tensor, unless explicitly overridden.


In [5]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.0455, 0.9518],
        [0.3280, 0.9822]]) 



**With random or constant values:**

`shape` is a tuple of tensor dimensions. In the functions below, it
determines the dimensionality of the output tensor.


In [6]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0510, 0.3882, 0.9645],
        [0.4620, 0.5708, 0.8696]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


------------------------------------------------------------------------


Tensor Attributes
=================

Tensor attributes describe their shape, datatype, and the device on
which they are stored.


In [7]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


------------------------------------------------------------------------


Tensor Operations
=================

Over 100 tensor operations, including transposing, indexing, slicing,
mathematical operations, linear algebra, random sampling, and more are
comprehensively described
[here](https://pytorch.org/docs/stable/torch.html).

Each of them can be run on the GPU (at typically higher speeds than on a
CPU). If you're using Colab, allocate a GPU by going to Edit \> Notebook
Settings.


In [8]:
# We move our tensor to the GPU if available
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else 'cpu'
tensor = tensor.to(device)
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: mps:0


**Standard numpy-like indexing and slicing:**


In [9]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Joining tensors** You can use `torch.cat` to concatenate a sequence of
tensors along a given dimension. See also
[torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html),
another tensor joining op that is subtly different from `torch.cat`.

- cat = glue tensors together side-by-side
- stack = put tensors into a new container dimension


In [10]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [11]:
t2 = torch.stack([tensor, tensor, tensor], dim=1)
print(t2)

tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])


**Multiplying tensors**


In [12]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


This computes the matrix multiplication between two tensors


In [13]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


**In-place operations** Operations that have a `_` suffix are in-place.
For example: `x.copy_(y)`, `x.t_()`, will change `x`.


In [14]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>NOTE:</strong></div>

<div style="background-color: #f3f4f7; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; padding-right: 10px">

<p>In-place operations save some memory, but can be problematic when computing derivatives because of an immediate lossof history. Hence, their use is discouraged.</p>

</div>



------------------------------------------------------------------------


Bridge with NumPy
=================

Tensors on the CPU and NumPy arrays can share their underlying memory
locations, and changing one will change the other.


Tensor to NumPy array
=====================


In [15]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.


In [16]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


NumPy array to Tensor
=====================


In [17]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the NumPy array reflects in the tensor.


In [18]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


# Convert a dataframe to Tensor

In [19]:
import pandas as pd

# Create a dataframe with house features and prices
data = {
    "Bedrooms": [2, 3, 4, 3, 5],
    "Bathrooms": [1, 2, 3, 2, 4],
    "Square_Feet": [900, 1500, 2200, 1800, 3000],
    "Age_Years": [20, 10, 5, 15, 2],
    "Garage": [0, 1, 2, 1, 3],
    "Price": [180000, 320000, 450000, 380000, 750000]
}

df = pd.DataFrame(data)

print(df)

   Bedrooms  Bathrooms  Square_Feet  Age_Years  Garage   Price
0         2          1          900         20       0  180000
1         3          2         1500         10       1  320000
2         4          3         2200          5       2  450000
3         3          2         1800         15       1  380000
4         5          4         3000          2       3  750000


In [21]:
all_values = df.values
print(all_values)

[[     2      1    900     20      0 180000]
 [     3      2   1500     10      1 320000]
 [     4      3   2200      5      2 450000]
 [     3      2   1800     15      1 380000]
 [     5      4   3000      2      3 750000]]


In [24]:
dataframe_tensor = torch.tensor(all_values, dtype = torch.int)
print(dataframe_tensor)

tensor([[     2,      1,    900,     20,      0, 180000],
        [     3,      2,   1500,     10,      1, 320000],
        [     4,      3,   2200,      5,      2, 450000],
        [     3,      2,   1800,     15,      1, 380000],
        [     5,      4,   3000,      2,      3, 750000]], dtype=torch.int32)


# The `unsqueeze` method

Often in the data the original feature tensors are one-dimensional, meaning each tensor contains a single sequence of values with shape `[x]`. Machine learning models in PyTorch often expect input features to be arranged as two-dimensional matrices, where each row represents one data sample and each column represents one feature. To achieve this structure, the `.unsqueeze(1)` method can be applied. This will add a new dimension at index 1, transforming the tensors from shape `[x]` into shape `[x, 1]`. As a result, each feature became a two-dimensional column vector, making the data suitable for concatenation into a feature matrix or for direct use in neural network models.

In [25]:
import torch

# Example 1D feature tensors
bedrooms = torch.tensor([2, 3, 4, 3, 5])
bathrooms = torch.tensor([1, 2, 3, 2, 4])
square_feet = torch.tensor([900, 1500, 2200, 1800, 3000])
age_years = torch.tensor([20, 10, 5, 15, 2])

# Reshape into 2D column vectors
bedrooms = bedrooms.unsqueeze(1)
bathrooms = bathrooms.unsqueeze(1)
square_feet = square_feet.unsqueeze(1)
age_years = age_years.unsqueeze(1)

# Display shapes
print("Bedrooms shape:", bedrooms.shape)
print("Bathrooms shape:", bathrooms.shape)
print("Square feet shape:", square_feet.shape)
print("Age years shape:", age_years.shape)


Bedrooms shape: torch.Size([5, 1])
Bathrooms shape: torch.Size([5, 1])
Square feet shape: torch.Size([5, 1])
Age years shape: torch.Size([5, 1])
